clear all
clc
syms theta1 theta3 L1 d2 L3 Le pi phi L0 L2 d1 theta2
% first goes alpha, then a, then d, then theta!

% this is correct
dh = sym([...
    0, 0, 0, theta1; ...
     -(-pi/2 + phi), 0, L1+d2, 0; ...
    -(-phi+ pi/2), 0, L3, theta3; ...
    0, Le, 0, 0
    ]);

% dh = sym([...
%     0, 0, 0, theta1; ...
%     pi/2 - phi, 0, L1+d2, 0; ...
%     phi - pi/2, 0, L3, theta3; ...
%     0, Le, 0, 0
%     ]);
% 
% dh = sym([...
%     0, 0, 0, theta1; ...
%     0, L1, d2, theta2; ...
%     0, L2, 0, theta3; ...
%     0, Le, 0, 0
%     ]);

% something with the distances is wrong?? Need to fix it!
T_forward = 1;
for i = 1:size(dh)
    T = sym([...
        cos(dh(i,4)), -sin(dh(i,4)), 0, dh(i,2); ...
        sin(dh(i,4))*cos(dh(i,1)), cos(dh(i,4))*cos(dh(i,1)), -sin(dh(i,1)), -sin(dh(i,1))*dh(i,3)
        sin(dh(i,4))*sin(dh(i,1)), cos(dh(i,4))*sin(dh(i,1)), cos(dh(i,1)), cos(dh(i,1))*dh(i,3)
        0, 0, 0, 1
        ]);
    T_forward = T_forward *T;
        T
     T * [0;0;0;1]
%T_forward  * [0;0;0;1]

end
T_forward
%HTR3plan()
%syms a
%diff(a, x)
